version: "2"

exclude_patterns:
  - "**/.*"
  - "**/LICENSE"
  - "**/*.md"
  - "**/composer.json"
  - "**/composer.lock"
  - "**/composer.phar"
  - "**/node_modules/"
  - "**/docker-compose.yml"
  - "**/Dockerfile*"
  - "**/*phpdoc*"
  - "**/*phpunit*"
  - "**/tests/"
  - "**/vendor/"
  - "docs/"
  - "**/examples/"

# pluginsの中で除外する場合はplugin名の直下に記述する
# plugins: 
#   phpcodesniffer:
#     enabled: true
#     exclude_patterns:
#      - "example/"
# 

plugins: 
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      standard: "PSR12"
      file_extensions: "php"

  phpmd:
    enabled: true
    config:
      file_extensions: "php"
