# Runnerとして利用するDockerコンテナイメージを指定
image: hazuki3417/ubuntu_nginx_php:latest

# job間で共有するディレクトリを指定する
cache:
  paths:
    - vendor/
    - docs/coverage
    - docs/phpdoc

stages:
  - prepare
  - build
  - test
  - generate
  - save
  - deploy

setting_composer:
  stage: prepare
  script: 
    - php composer.phar install
    - php composer.phar dumpautoload

check:
  stage: prepare
  script: 
    - export

test_php:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"' # シングルクォーテーションで囲わないと行けない
      changes: #二重引用符で囲わなければ反応しない
      - "src/*"
      - "tests/*"
      when: always
      # 上記の条件に一致したときのみjobを実行
  stage: test
  script: 
    # php unittestを実行
    - ./vendor/bin/phpunit -c ./phpunit.xml 

coverage_php:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "src/*"
      - "tests/*"
      when: always
      # 上記の条件に一致したときのみjobを実行
  stage: generate
  script:
    # php coverageを出力
    - phpdbg -qrr ./vendor/bin/phpunit -c ./phpunit.xml

document_php:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "src/*"
      - "tests/*"
      when: always
      # 上記の条件に一致したときのみjobを実行
  stage: generate
  script:
    # php documentを出力
    - ./vendor/bin/phpdoc -c ./phpdoc.dist.xml


save_documents:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "src/*"
      - "tests/*"
      when: manual
      allow_failure: true
      # パイプラインの失敗を許容するかどうか true:許可する false:許可しない
      # 許可した場合はスキップ扱いとなる
  stage: save
  script: 
    # Gitのセットアップ
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
    - git remote set-url origin https://gitlab-ci-token:$GITLAB_API_ACCESS_TOKEN@${CI_REPOSITORY_URL##*@}
    - git checkout $CI_COMMIT_REF_NAME
    # git logを出力（デバッグ用）
    # - git log --max-count=5
    # 差分があるときはコミット
    - git add ./docs
    - |-
      if [ `git status -s | wc -l` -gt 0 ]; then
          git commit -m "Commit documents generated by GitLab CI"
          git push --push-option=ci.skip origin $CI_COMMIT_REF_NAME
      fi
