version: "3.0"

services:
  web:
    hostname: php-measurement
    image: php:5.6-cli
    # image: hazuki3417/ubuntu_nginx_php:latest
    container_name: php-measurement
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    tty: true
