name: generate-docs

on:
  push:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master


    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest


    - name: Generate Document
      run: php ./vendor/bin/phpdoc -c ./phpdoc.xml


    # [Reference]
    # https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_CLI_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_CLI_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-1

    - name: Upload Document Files
      env: 
        S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
      run: |
        aws s3 sync ./docs/phpdoc s3://$S3_BUCKET_NAME/phpdoc
